# 1

In [102]:
import pandas as pd
import re
import numpy as np
import math

In [69]:
diem = pd.read_csv('../Education_dataset_V2/diem_Thu.csv', encoding='ISO-8859-1')
# Xóa khoảng trắng ở trước tên cột
diem = diem.rename(columns=lambda x: x.strip())

In [70]:
diem.info

<bound method DataFrame.info of                                             mssv   mamh         malop  sotc  \
0       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  CARC1        K1C1_2     3   
1       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  CSC21        K1C1_2     5   
2       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  ENG02        K1C1_2     0   
3       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  MAT21        K1C1_2     4   
4       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  PEDU1        K1C1_2     0   
...                                          ...    ...           ...   ...   
674268  78F971C7XPvAibaEXe/qyMkGG2RlFrgIY6/9Nnnk  IE101  IE101.N11.LT     3   
674269  35A4B1C2XPvAibaEXe/VxWgTgtHe07+vkN6++USd  IE101  IE101.N11.LT     3   
674270  7CDE61ABXPvAibaEXe/VxWgTgtHe04Encl5UmaMi  IE101  IE101.N11.LT     3   
674271  658FB4D5XPvAibaEXe/VxWgTgtHe02gf1ImYGwpE  IE101  IE101.N11.LT     3   
674272  7114E632XPvAibaEXe/VxWgTgtHe08jgqfqtydmc  IE101  IE101.N11.LT     3   

        hocky  namh

In [71]:
monhoc = diem.drop(['malop','mamh_tt','diem_qt','diem_th','diem_gk','diem_ck','tinhtrang'], axis=1)

In [72]:
monhoc

mssv   mamh  sotc  hocky  namhoc  \
0       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  CARC1     3      1    2006   
1       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  CSC21     5      1    2006   
2       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  ENG02     0      1    2006   
3       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  MAT21     4      1    2006   
4       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  PEDU1     0      1    2006   
...                                          ...    ...   ...    ...     ...   
674268  78F971C7XPvAibaEXe/qyMkGG2RlFrgIY6/9Nnnk  IE101     3      1    2022   
674269  35A4B1C2XPvAibaEXe/VxWgTgtHe07+vkN6++USd  IE101     3      1    2022   
674270  7CDE61ABXPvAibaEXe/VxWgTgtHe04Encl5UmaMi  IE101     3      1    2022   
674271  658FB4D5XPvAibaEXe/VxWgTgtHe02gf1ImYGwpE  IE101     3      1    2022   
674272  7114E632XPvAibaEXe/VxWgTgtHe08jgqfqtydmc  IE101     3      1    2022   

        diem_hp  trangthai  
0           2.0          2  
1           5.0          1  
2           5.5          1  
3           6.5          1  
4           7.0          1  
...         ...        ...  
674268      7.6          1  
674269      7.9          1  
674270      8.1          1  
674271      6.9          1  
674272      7.7          1  

[674273 rows x 7 columns]

## XỬ LÍ

In [73]:
# Xóa khoảng trắng ở trước tên môn
monhoc['mamh'] = monhoc['mamh'].str.replace(' ', '')

#CS1113 = CS113
monhoc['mamh'] = monhoc['mamh'].replace({'CS1113': 'CS113'})

In [74]:
print(monhoc['mamh'].value_counts())
monhoc['mamh'].unique()

IT002     15960
MA003     15759
IT001     15632
IT003     14615
IT004     13166
          ...  
CS4344        3
IS5100        3
MAT24         3
OSYS2         2
ME001         2
Name: mamh, Length: 638, dtype: int64


array(['CARC1', 'CSC21', 'ENG02', 'MAT21', 'PEDU1', 'PHIL2', 'PHY01',
       'DBSS1', 'DSAL1', 'ENG03', 'MAT22', 'OOPT2', 'PEDU2', 'PHY22',
       'CNET1', 'CSKI1', 'ENG04', 'MAT23', 'MLPE2', 'OSYS1', 'WINP1',
       'CS104', 'CS105', 'CS106', 'MAT04', 'VCPL1', 'CE105', 'CS103',
       'CS107', 'CS108', 'DSAL2', 'HCMT1', 'CS102', 'CS109', 'CS211',
       'CS311', 'SOCI1', 'CS013', 'CS019', 'IS207', 'ITEM1', 'CS101',
       'CS401', 'CS403', 'CS503', 'SE104', 'CS212', 'CS014', 'CS402',
       'CS004', 'CS226', 'PHIL1', 'STA01', 'CS322', 'VCPH1', 'OOPT1',
       'ENG05', 'CE101', 'CE102', 'CE108', 'CE103', 'CE104', 'CE106',
       'CE107', 'CE109', 'CE110', 'CE111', 'CE112', 'CE113', 'CE114',
       'CE115', 'CE204', 'ITEW1', 'CE116', 'CE301', 'CE501', 'SMET2',
       'CE314', 'CE505', 'IS203', 'IS102', 'IS103', 'IS201', 'IS204',
       'IS206', 'IS104', 'IS105', 'IS205', 'IS208', 'IS106', 'IS107',
       'IS202', 'IS301', 'IS311', 'IS305', 'IS306', 'IS501', 'IS101',
       'IS505', 'CE2

In [75]:
monhoc['mamh'] = monhoc['mamh'].astype(str)  # Chuyển đổi kiểu dữ liệu thành chuỗi
# tách độ khó
monhoc['tenmon'] = monhoc['mamh'].apply(lambda x: re.split('\d+', x)[0].strip())
monhoc['dokho'] = monhoc['mamh'].apply(lambda x: int(re.search('(\d+)', x).group(1)[:1]) if re.search('(\d+)', x) else '')

In [76]:
# định nghĩa makhoa: 
# 0 - môn chung
# 1 - KHMT
# 2 - CNPM 
# 3 - HTTT
# 4 - MMT
# 5 - KTMT
# 6 - KTTT

#LƯU Ý:
# Sự phân chia trên có thể chưa chính xác hoàn toán
# Có các môn độc lập hoặc tương đương nhau, nhưng được tách ra và được quản lí bởi các khoa khác nhau
# Có các môn học tuy giống nhau nhưng khác mã được sửa đổi và tích hợp từ các khóa cũ

# Các môn IT thuộc rất nhiều khoa quản lí
# vd: IT004 Hướng đối tượng IT005 mạng máy tính IT006 kiến trúc máy tính
# nhưng vì đều có tính chất là các môn nhập môn và là môn tiên quyết
# nên có thể xem như các môn chung

def encode_khoa(monhoc):
    if monhoc in ['VCPL','VCPH', 'SOCI','PHIL','PEDU', 'MLPE', 'MAT','LIA','JAN','ITEW', 'HCMT','ENG', 'ENGA', 'ENGBT', 'ENGL','ADENG','ITEM','IT', 'EN', 'ENBT', 'MA', 'PE',"SMET",'SS']:
        return 0
    elif monhoc in ['DSAL','CSKI', 'CSC','CSBU', 'CS']:
        return 1
    elif monhoc in ['OOPT', 'SE','WINP']:
        return 2
    elif monhoc in ['STA','SP', 'MKTG','IS','INT','IEM', 'ECON', 'DBSS','ENGL','ADENG','EC','IS','MATH','MSIS','PHYS','SC','SPCH','STAT','ACCT']:
        return 3
    elif monhoc in ['OSYS','CNET','CNBU','NT','MAH']:
        return 4
    elif monhoc in ['CARC','PH','CE']:
        return 5
    elif monhoc in ['DS','CU','IE']:
        return 6
    else:
        return None
    
#tạo thuộc tính makhoa
monhoc['makhoa'] = monhoc['tenmon'].apply(encode_khoa)

In [77]:
monhoc = monhoc[~monhoc['trangthai'].isin([0, 4, 5])]
monhoc['trangthai'].unique()

array([2, 1, 3], dtype=int64)

In [78]:
monhoc = monhoc[monhoc['dokho'] != '']
monhoc['dokho'].unique()

array([1, 2, 0, 3, 4, 5], dtype=object)

In [79]:
monhoc['sotc'].unique()

array([ 3,  5,  0,  4,  2, 10,  1,  8,  6, 65, 64], dtype=int64)

In [80]:
# Kiểm tra tính đồng bộ của cột "sotc" trong mỗi môn học

inconsistent_mh = monhoc.groupby('mamh')['sotc'].nunique().loc[lambda x: x > 1].index.tolist()
if len(inconsistent_mh) > 0:
    print("Có môn học không đồng bộ về sotc:", inconsistent_mh)
    print()

   # Tạo bảng đếm giá trị sotc theo môn học
    sotc_counts = monhoc.groupby('mamh')['sotc'].value_counts().reset_index(name='count')

    # Lặp qua từng môn học không đồng bộ
    for mamh in inconsistent_mh:
        sotc_values = sotc_counts.loc[sotc_counts['mamh'] == mamh, 'sotc'].tolist()
        sotc_counts_grouped = sotc_counts.loc[sotc_counts['mamh'] == mamh, ['sotc', 'count']].groupby('sotc').sum()
        unique_sotc = sotc_counts_grouped.index.tolist()
        count_values = sotc_counts_grouped['count'].tolist()

        # Hiển thị thông tin số lượng dữ liệu cho từng giá trị sotc
        print(f"Môn học {mamh} có các giá trị sotc khác nhau và số lượng dữ liệu tương ứng:")
        for i in range(len(unique_sotc)):
            print(f"- Giá trị sotc {unique_sotc[i]}: {count_values[i]} dữ liệu")
else:
    print("Tất cả các môn học đều đồng bộ về sotc.")

Có môn học không đồng bộ về sotc: ['BUS1125', 'CARC1', 'CE005', 'CE101', 'CE103', 'CE105', 'CE107', 'CE109', 'CE115', 'CE118', 'CE119', 'CE121', 'CE124', 'CE202', 'CE206', 'CE211', 'CE212', 'CE221', 'CE222', 'CE313', 'CE315', 'CE316', 'CE501', 'CNBU003', 'CNET1', 'CS004', 'CS005', 'CS101', 'CS102', 'CS106', 'CS107', 'CS109', 'CS110', 'CS111', 'CS112', 'CS113', 'CS114', 'CS214', 'CS217', 'CS221', 'CS222', 'CS225', 'CS226', 'CS231', 'CS232', 'CS2433', 'CS331', 'CS332', 'CS336', 'CS351', 'CS352', 'CS371', 'CS372', 'CS401', 'CS404', 'CS405', 'CS406', 'CS407', 'CS408', 'CS412', 'CS417', 'CS4273', 'CS5030', 'CS519', 'CS521', 'CS523', 'CS526', 'CSBU003', 'CSBU007', 'CSBU101', 'CSBU102', 'CSBU105', 'CSC01', 'DBSS1', 'DS005', 'EC005', 'EC202', 'EC213', 'EC214', 'EC222', 'EC229', 'EC301', 'EC311', 'EC312', 'EN001', 'EN002', 'EN003', 'EN004', 'EN005', 'EN006', 'ENG01', 'ENG02', 'ENG03', 'ENG04', 'ENG05', 'ENGA2', 'ENGL1213', 'HCMT1', 'IE005', 'IE101', 'IE102', 'IE104', 'IE202', 'IE204', 'IE206', 

In [81]:
# Tạo bảng đếm giá trị sotc theo môn học
sotc_counts = monhoc.groupby('mamh')['sotc'].value_counts().reset_index(name='count')

# Lặp qua từng môn học
for mamh in monhoc['mamh'].unique():
    # Lấy giá trị 'sotc' có số lượng dữ liệu lớn nhất cho môn học hiện tại
    max_sotc = sotc_counts.loc[sotc_counts['mamh'] == mamh, 'sotc'].iloc[0]
    # Đồng bộ giá trị 'sotc' của môn học về giá trị max
    monhoc.loc[monhoc['mamh'] == mamh, 'sotc'] = max_sotc


In [82]:
monhoc.info

<bound method DataFrame.info of                                             mssv   mamh  sotc  hocky  namhoc  \
0       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  CARC1     3      1    2006   
1       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  CSC21     5      1    2006   
2       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  ENG02     4      1    2006   
3       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  MAT21     4      1    2006   
4       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  PEDU1     0      1    2006   
...                                          ...    ...   ...    ...     ...   
674268  78F971C7XPvAibaEXe/qyMkGG2RlFrgIY6/9Nnnk  IE101     3      1    2022   
674269  35A4B1C2XPvAibaEXe/VxWgTgtHe07+vkN6++USd  IE101     3      1    2022   
674270  7CDE61ABXPvAibaEXe/VxWgTgtHe04Encl5UmaMi  IE101     3      1    2022   
674271  658FB4D5XPvAibaEXe/VxWgTgtHe02gf1ImYGwpE  IE101     3      1    2022   
674272  7114E632XPvAibaEXe/VxWgTgtHe08jgqfqtydmc  IE101     3      1    2022   

       

In [83]:
# Kiểm tra MỘT LẦN NỮA tính đồng bộ của cột "sotc" trong bảng mh

inconsistent_mh = monhoc.groupby('mamh')['sotc'].nunique().loc[lambda x: x > 1].index.tolist()
if len(inconsistent_mh) > 0:
    print("Có môn học không đồng bộ về sotc:", inconsistent_mh)
    print()

    sotc_counts = monhoc.groupby('mamh')['sotc'].value_counts().reset_index(name='count')

    for mamh in inconsistent_mh:
        sotc_values = sotc_counts.loc[sotc_counts['mamh'] == mamh, 'sotc'].tolist()
        sotc_counts_grouped = sotc_counts.loc[sotc_counts['mamh'] == mamh, ['sotc', 'count']].groupby('sotc').sum()
        unique_sotc = sotc_counts_grouped.index.tolist()
        count_values = sotc_counts_grouped['count'].tolist()

        print(f"Môn học {mamh} có các giá trị sotc khác nhau và số lượng dữ liệu tương ứng:")
        for i in range(len(unique_sotc)):
            print(f"- Giá trị sotc {unique_sotc[i]}: {count_values[i]} dữ liệu")
else:
    print("Tất cả các môn học đều đồng bộ về sotc.")

Tất cả các môn học đều đồng bộ về sotc.


In [84]:
monhoc['sotc'].unique()

array([ 3,  5,  4,  0,  2, 10,  1,  8, 64], dtype=int64)

In [85]:
# Sửa lỗi sotc bất thường

# 8: CNBU003(dự án nghiên cứu)
# 10: các môn KLTN

# 0: ENG04 ENGA2 PE
monhoc.loc[monhoc['mamh'] == 'ENG04', 'sotc'] = 4
monhoc.loc[monhoc['mamh'] == 'ENGA2', 'sotc'] = 4

# 64: CSBU101 CSBU102 CSBU105
monhoc.loc[monhoc['mamh'] == 'CSBU101', 'sotc'] = 4
monhoc.loc[monhoc['mamh'] == 'CSBU102', 'sotc'] = 4
monhoc.loc[monhoc['mamh'] == 'CSBU105', 'sotc'] = 4

monhoc['sotc'].unique()

array([ 3,  5,  4,  0,  2, 10,  1,  8], dtype=int64)

In [86]:
# Thử in ra mamh kiểm tra phép tính đồng bộ tc
print(monhoc[monhoc['mamh']=='SS004'])

                                            mssv   mamh  sotc  hocky  namhoc  \
187070  8044D4F3XPvAibaEXe/UXxbMptU3XVb9n+PrHuEA  SS004     2      2    2013   
187071  F832105BXPvAibaEXe+cD1fKElqxL8dha7yinstM  SS004     2      2    2013   
187072  C47110EFXPvAibaEXe/PGAaNNWvbUF95KJJbQ6Bs  SS004     2      2    2013   
187073  8219EA1DXPvAibaEXe/PGAaNNWvbUAwbuGIAPcg8  SS004     2      2    2013   
187074  A2A984F7XPvAibaEXe9X5bpEKoa0mp7uV1IrtAed  SS004     2      2    2013   
...                                          ...    ...   ...    ...     ...   
668558  F8008CD6XPvAibaEXe+whDYzxQ4teTdCU/S775jt  SS004     2      1    2022   
668559  422DBDDCXPvAibaEXe+wzULHNH0ZAWI0zvn/bI4R  SS004     2      1    2022   
668560  0F95BF11XPvAibaEXe85pnNqK7QfqrW38OxsyfdO  SS004     2      1    2022   
668561  0F9FC751XPvAibaEXe+Hr3DoUa42WTXXAFLaUiQG  SS004     2      1    2022   
668562  08FD8863XPvAibaEXe+DniE7HQhZziH82X2C3hNu  SS004     2      1    2022   

        diem_hp  trangthai tenmon dokho

In [90]:
monhoc.drop("tenmon",axis=1)

mssv   mamh  sotc  hocky  namhoc  \
0       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  CARC1     3      1    2006   
1       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  CSC21     5      1    2006   
2       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  ENG02     4      1    2006   
3       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  MAT21     4      1    2006   
4       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  PEDU1     0      1    2006   
...                                          ...    ...   ...    ...     ...   
674268  78F971C7XPvAibaEXe/qyMkGG2RlFrgIY6/9Nnnk  IE101     3      1    2022   
674269  35A4B1C2XPvAibaEXe/VxWgTgtHe07+vkN6++USd  IE101     3      1    2022   
674270  7CDE61ABXPvAibaEXe/VxWgTgtHe04Encl5UmaMi  IE101     3      1    2022   
674271  658FB4D5XPvAibaEXe/VxWgTgtHe02gf1ImYGwpE  IE101     3      1    2022   
674272  7114E632XPvAibaEXe/VxWgTgtHe08jgqfqtydmc  IE101     3      1    2022   

        diem_hp  trangthai dokho  makhoa  
0           2.0          2     1     5.0  
1           5.0          1     2     1.0  
2           5.5          1     0     0.0  
3           6.5          1     2     0.0  
4           7.0          1     1     0.0  
...         ...        ...   ...     ...  
674268      7.6          1     1     6.0  
674269      7.9          1     1     6.0  
674270      8.1          1     1     6.0  
674271      6.9          1     1     6.0  
674272      7.7          1     1     6.0  

[655228 rows x 9 columns]

# 2

In [91]:
# Tách dữ liệu từ trước 2022 và từ 2022 trở đi
monhoc_test = monhoc[monhoc['namhoc'] >= 2022]
monhoc_train = monhoc[monhoc['namhoc'] < 2022]

In [92]:
monhoc_train

mssv   mamh  sotc  hocky  namhoc  \
0       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  CARC1     3      1    2006   
1       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  CSC21     5      1    2006   
2       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  ENG02     4      1    2006   
3       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  MAT21     4      1    2006   
4       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  PEDU1     0      1    2006   
...                                          ...    ...   ...    ...     ...   
659158  09DE3A51XPvAibaEXe/GEP39G15BdRSEDU3D3+LV  SS009     2      1    2021   
659159  11A997D7XPvAibaEXe+NDJhRHiaomek63bkrNRWH  SS010     2      2    2021   
659160  D842888FXPvAibaEXe/TkCpSS/6Lh9dKiP5QFUuk  SS010     2      2    2021   
659161  7799CABBXPvAibaEXe/33FMzfi5mecGbtNM11HXT  SS010     2      2    2021   
659162  5D749C31XPvAibaEXe+NyYotv4FWdSswpY7zzBtF  IS353     3      1    2021   

        diem_hp  trangthai tenmon dokho  makhoa  
0           2.0          2   CARC     1     5.0  
1           5.0          1    CSC     2     1.0  
2           5.5          1    ENG     0     0.0  
3           6.5          1    MAT     2     0.0  
4           7.0          1   PEDU     1     0.0  
...         ...        ...    ...   ...     ...  
659158      0.0          1     SS     0     0.0  
659159      NaN          1     SS     0     0.0  
659160      0.0          1     SS     0     0.0  
659161      0.0          2     SS     0     0.0  
659162      0.0          1     IS     3     3.0  

[618333 rows x 10 columns]

In [93]:
monhoc_train

mssv   mamh  sotc  hocky  namhoc  \
0       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  CARC1     3      1    2006   
1       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  CSC21     5      1    2006   
2       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  ENG02     4      1    2006   
3       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  MAT21     4      1    2006   
4       2117714DXPvAibaEXe8WaPZ0jKz4ts3P6QyM9Ybc  PEDU1     0      1    2006   
...                                          ...    ...   ...    ...     ...   
659158  09DE3A51XPvAibaEXe/GEP39G15BdRSEDU3D3+LV  SS009     2      1    2021   
659159  11A997D7XPvAibaEXe+NDJhRHiaomek63bkrNRWH  SS010     2      2    2021   
659160  D842888FXPvAibaEXe/TkCpSS/6Lh9dKiP5QFUuk  SS010     2      2    2021   
659161  7799CABBXPvAibaEXe/33FMzfi5mecGbtNM11HXT  SS010     2      2    2021   
659162  5D749C31XPvAibaEXe+NyYotv4FWdSswpY7zzBtF  IS353     3      1    2021   

        diem_hp  trangthai tenmon dokho  makhoa  
0           2.0          2   CARC     1     5.0  
1           5.0          1    CSC     2     1.0  
2           5.5          1    ENG     0     0.0  
3           6.5          1    MAT     2     0.0  
4           7.0          1   PEDU     1     0.0  
...         ...        ...    ...   ...     ...  
659158      0.0          1     SS     0     0.0  
659159      NaN          1     SS     0     0.0  
659160      0.0          1     SS     0     0.0  
659161      0.0          2     SS     0     0.0  
659162      0.0          1     IS     3     3.0  

[618333 rows x 10 columns]

In [105]:
# Nhóm dữ liệu theo mssv và thu thập thông tin môn học
grouped_data = monhoc_test.groupby('mssv').agg({
    'mamh': lambda x: x.tolist(),
    'makhoa': lambda x: x.tolist(),
    'sotc': lambda x: x.tolist(),
    'dokho': lambda x: x.tolist(),
    'trangthai': lambda x: x.tolist()
})


In [106]:
# Tạo danh sách các sinh viên với thông tin môn học
sinhvien_list = []
for mssv, row in grouped_data.iterrows():
    sinhvien = {
        'mssv': mssv,
        #thong tin mon hoc
        'mamh': row['mamh'],
        'makhoa': row['makhoa'],
        'sotc': row['sotc'],
        'dokho': row['dokho'],
        'trangthai': row['trangthai'],

        #thong tin hoc phan cua sv
        'namhoc': monhoc_test.loc[monhoc_test['mssv'] == mssv, 'namhoc'].tolist(),
        'hocky': monhoc_test.loc[monhoc_test['mssv'] == mssv, 'hocky'].tolist(),
        'diemtb': monhoc_test.loc[monhoc_test['mssv'] == mssv, 'diem_hp'].tolist()
    }
    sinhvien_list.append(sinhvien)




In [107]:
with open('dssv_test.txt', 'w') as file:
    for i, sinhvien in enumerate(sinhvien_list, start=1):
        file.write("Sinh_vien_{}: \n".format(i))
        file.write("MSSV: " + str(sinhvien['mssv']) + "\n")
        file.write("monhoc: " + str(sinhvien['mamh']) + "\n")
        khoa_nguyen = [int(value) if not math.isnan(value) else 0 for value in sinhvien['makhoa']]
        file.write("khoa: " + str(khoa_nguyen) + "\n")

        file.write("sotc: " + str(sinhvien['sotc']) + "\n")
        file.write("dokho: " + str(sinhvien['dokho']) + "\n")
        file.write("trangthai: " + str(sinhvien['trangthai']) + "\n")
        file.write("namhoc: " + str(sinhvien['namhoc']) + "\n")
        file.write("hocky: " + str(sinhvien['hocky']) + "\n")
        file.write("diemtb: " + str(sinhvien['diemtb']) + "\n")
        file.write("\n")

In [108]:
# Chuyển đổi danh sách sinh viên thành DataFrame
df = pd.DataFrame(sinhvien_list)

# Ghi dữ liệu vào tệp CSV
df.to_csv('dssv_test.csv', index=False)

In [109]:
# with open('danh_sach_sinh_vien.txt', 'r') as file:
#     content = file.read()
#     print(content)

# 